### ISSUE TITLE
express version fails when pf9-express hasn't been initialized

### ISSUE THREAD

**Issue by tomchris** [platform9/express-cli#12]
Handle error correctly instead of failing.

tomchris@tomchris-pf9-mbp:~/Development/express-cli (jb4free/pmk-cli) $express version
Traceback (most recent call last):
  File "/usr/local/bin/express", line 11, in <module>
    load_entry_point('express-cli', 'console_scripts', 'express')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/tomchris/Development/express-cli/pf9/express.py", line 82, in version
    with open(dir_path + 'version', 'r') as v:
IOError: [Errno 2] No such file or directory: '/Users/tomchris/pf9/pf9-express/version'

**Comment by tomchris** [comment]
Closed by #13
